# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(581, 514)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sifreLine = QtWidgets.QLineEdit(self.centralwidget)
        self.sifreLine.setGeometry(QtCore.QRect(100, 280, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.sifreLine.setFont(font)
        self.sifreLine.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.sifreLine.setStyleSheet("color: rgb(255, 255, 255);")
        self.sifreLine.setEchoMode(QtWidgets.QLineEdit.Password)
        self.sifreLine.setObjectName("sifreLine")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 30, 241, 111))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.kullaniciAdiLine = QtWidgets.QLineEdit(self.centralwidget)
        self.kullaniciAdiLine.setGeometry(QtCore.QRect(100, 180, 371, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.kullaniciAdiLine.setFont(font)
        self.kullaniciAdiLine.setStyleSheet("color:rgb(255, 255, 255)")
        self.kullaniciAdiLine.setObjectName("kullaniciAdiLine")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.girisButon = QtWidgets.QPushButton(self.centralwidget)
        self.girisButon.setGeometry(QtCore.QRect(220, 340, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.girisButon.setFont(font)
        self.girisButon.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(77, 77, 77);")
        self.girisButon.setObjectName("girisButon")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 230, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.kayitButon = QtWidgets.QPushButton(self.centralwidget)
        self.kayitButon.setGeometry(QtCore.QRect(220, 390, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.kayitButon.setFont(font)
        self.kayitButon.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(77, 77, 77);")
        self.kayitButon.setObjectName("kayitButon")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Giriş Ekranı"))
        self.label.setText(_translate("MainWindow", "Hoş Geldiniz!"))
        self.label_2.setText(_translate("MainWindow", "Kullanıcı Adı:"))
        self.girisButon.setText(_translate("MainWindow", "Giriş Yap"))
        self.label_3.setText(_translate("MainWindow", "Şifre:"))
        self.kayitButon.setText(_translate("MainWindow", "Kayıt Ol"))
