# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'İzlemelistesi.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_izlemelistem(object):
    def setupUi(self, izlemelistem):
        izlemelistem.setObjectName("izlemelistem")
        izlemelistem.resize(601, 488)
        self.tablo = QtWidgets.QTableWidget(izlemelistem)
        self.tablo.setGeometry(QtCore.QRect(0, 0, 611, 491))
        self.tablo.setObjectName("tablo")
        self.tablo.setColumnCount(6)
        self.tablo.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablo.setHorizontalHeaderItem(5, item)

        self.retranslateUi(izlemelistem)
        QtCore.QMetaObject.connectSlotsByName(izlemelistem)

    def retranslateUi(self, izlemelistem):
        _translate = QtCore.QCoreApplication.translate
        izlemelistem.setWindowTitle(_translate("izlemelistem", "İzleme Listem"))
        item = self.tablo.horizontalHeaderItem(0)
        item.setText(_translate("izlemelistem", "Film Adı"))
        item = self.tablo.horizontalHeaderItem(1)
        item.setText(_translate("izlemelistem", "Yönetmeni"))
        item = self.tablo.horizontalHeaderItem(2)
        item.setText(_translate("izlemelistem", "Film Türü"))
        item = self.tablo.horizontalHeaderItem(3)
        item.setText(_translate("izlemelistem", "Yapım Yılı"))
        item = self.tablo.horizontalHeaderItem(4)
        item.setText(_translate("izlemelistem", "Süresi"))
        item = self.tablo.horizontalHeaderItem(5)
        item.setText(_translate("izlemelistem", "Yapım Yeri"))
