# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'İzlemegecmisi.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(712, 488)
        self.izlemegecmisi = QtWidgets.QTableWidget(Form)
        self.izlemegecmisi.setGeometry(QtCore.QRect(0, 0, 711, 491))
        self.izlemegecmisi.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.izlemegecmisi.setObjectName("izlemegecmisi")
        self.izlemegecmisi.setColumnCount(7)
        self.izlemegecmisi.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.izlemegecmisi.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.izlemegecmisi.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.izlemegecmisi.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.izlemegecmisi.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.izlemegecmisi.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.izlemegecmisi.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.izlemegecmisi.setHorizontalHeaderItem(6, item)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "İzleme Geçmişi"))
        item = self.izlemegecmisi.horizontalHeaderItem(0)
        item.setText(_translate("Form", "İzleme Tarihi"))
        item = self.izlemegecmisi.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Film Adı"))
        item = self.izlemegecmisi.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Yönetmeni"))
        item = self.izlemegecmisi.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Film Türü"))
        item = self.izlemegecmisi.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Yapım Yılı"))
        item = self.izlemegecmisi.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Süresi"))
        item = self.izlemegecmisi.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Yapım Yeri"))
